//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryList()
        {
            this.InventoryItemtbls = new HashSet<InventoryItemtbl>();
        }
    
        public int InventoryListId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string UnitType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItemtbl> InventoryItemtbls { get; set; }
    }
}
