//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItemtbl
    {
        public int InventoryListId { get; set; }
        public string Price { get; set; }
        public string DateOfBuying { get; set; }
        public string Location { get; set; }
        public string Quantity { get; set; }
        public string UnitType { get; set; }
        public int InventoryItemId { get; set; }
    
        public virtual InventoryList InventoryList { get; set; }
    }
}
