//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int User_ID { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public Nullable<int> User_ID_Ref { get; set; }
    }
}
