//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedInventoryDetailsTbl
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int InventoryItemId { get; set; }
        public Nullable<int> AmountOfUsed { get; set; }
        public string UnitType { get; set; }
        public string ActivityType { get; set; }
        public string Date { get; set; }
        public string Location { get; set; }
    
        public virtual User_Details User_Details { get; set; }
    }
}
