//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiInventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int User_ID_Ref { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_ID { get; set; }
        public string User_Type { get; set; }
    }
}
